name: AegisOps DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # -------------------------
    # 🐍 Python Setup
    # -------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    # -------------------------
    # 🔐 Gitleaks (Secrets Scan)
    # -------------------------
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    # -------------------------
    # 🛡️ Bandit (Python Security Scan)
    # -------------------------
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r backend -ll

    # -------------------------
    # 🐳 Docker Build
    # -------------------------
    - name: Build Docker Image
      run: |
        docker build -t aegisops-ai ./backend

        # -------------------------
    # ☁️ Configure AWS
    # -------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # -------------------------
    # 🐳 Login to ECR
    # -------------------------
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # -------------------------
    # 🚀 Push Docker Image
    # -------------------------
    - name: Build, Tag, Push Image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

        docker tag aegisops-ai:latest $IMAGE_URI:latest
        docker push $IMAGE_URI:latest

    # -------------------------
    # 🔍 Trivy (Container Scan)
    # -------------------------
    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "aegisops-ai"
        format: "table"
        exit-code: "0"
