name: AegisOps DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # -------------------------
    # 🐍 Python Setup
    # -------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    # -------------------------
    # 🔐 Gitleaks (Secrets Scan)
    # -------------------------
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    # -------------------------
    # 🛡️ Bandit (Python Security Scan)
    # -------------------------
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r backend -ll

    # -------------------------
    # 🐳 Docker Build
    # -------------------------
    - name: Build Docker Image
      run: |
        docker build -t aegisops-ai ./backend

    # -------------------------
    # 🔍 Trivy (Container Scan)
    # -------------------------
    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "aegisops-ai"
        format: "table"
        exit-code: "0"
